# Generated by Django 3.2.9 on 2021-12-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=40)),
                ('isAdmin', models.BooleanField(blank=True, default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('module_name', models.CharField(default='', max_length=180)),
                ('module_version', models.CharField(default='', max_length=20)),
                ('module_ID', models.CharField(default='', max_length=255)),
                ('action', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ModulePackage',
            fields=[
                ('Name', models.CharField(default='', max_length=180)),
                ('Version', models.CharField(default='0.0.0', max_length=20)),
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Content', models.CharField(blank=True, max_length=10285760, null=True)),
                ('URL', models.CharField(blank=True, max_length=2048, null=True)),
                ('JSProgram', models.TextField(default='', max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(default='', max_length=255)),
                ('net_score', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10)),
                ('ramp_up_score', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10)),
                ('correctness_score', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10)),
                ('bus_factor_score', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10)),
                ('responsiveness_score', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10)),
                ('dependency_score', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10)),
                ('license_score', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
