# Generated by Django 3.2.9 on 2021-12-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePackage',
            fields=[
                ('Name', models.CharField(default='', max_length=300)),
                ('Version', models.CharField(default='0.0.0', max_length=20)),
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Content', models.CharField(blank=True, max_length=10285760, null=True)),
                ('URL', models.CharField(blank=True, max_length=2048, null=True)),
                ('JSProgram', models.TextField(default='', max_length=1000000)),
            ],
        ),
    ]
