# Generated by Django 3.2.9 on 2021-11-23 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20211122_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulepackage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='modulepackage',
            name='version',
        ),
    ]
