# Generated by Django 3.2.9 on 2021-12-08 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_api', '0003_modulehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulehistory',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.modulepackage'),
        ),
        migrations.AlterField(
            model_name='modulehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
