# Generated by Django 3.2.9 on 2021-12-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20211207_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulehistory',
            name='module',
        ),
        migrations.RemoveField(
            model_name='modulehistory',
            name='user',
        ),
        migrations.AddField(
            model_name='modulehistory',
            name='isAdmin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='modulehistory',
            name='module_ID',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='modulehistory',
            name='module_name',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='modulehistory',
            name='module_version',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='modulehistory',
            name='username',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='modulepackage',
            name='Name',
            field=models.CharField(default='', max_length=180),
        ),
    ]
