# Generated by Django 3.2.9 on 2021-11-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20211122_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepackage',
            name='content',
            field=models.CharField(default='', max_length=40000000),
        ),
        migrations.AddField(
            model_name='modulepackage',
            name='version',
            field=models.CharField(default='0.0.0', max_length=20),
        ),
    ]
