# Generated by Django 3.2.9 on 2021-12-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_auto_20211122_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepackage',
            name='js_program',
            field=models.CharField(blank=True, max_length=10000000),
        ),
        migrations.AddField(
            model_name='modulepackage',
            name='url',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='modulepackage',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
