# Generated by Django 3.2.9 on 2021-12-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_modulerank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulerank',
            name='bus_factor_score',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='modulerank',
            name='correctness_score',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='modulerank',
            name='dependency_score',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='modulerank',
            name='license_score',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='modulerank',
            name='net_score',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='modulerank',
            name='ramp_up_score',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='modulerank',
            name='responsiveness_score',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
