# Generated by Django 3.2.9 on 2021-12-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_alter_modulepackage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepackage',
            name='content',
            field=models.CharField(blank=True, max_length=40000000),
        ),
        migrations.AlterField(
            model_name='modulepackage',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modulepackage',
            name='js_program',
            field=models.CharField(default='', max_length=10000000),
        ),
    ]
