# Generated by Django 3.2.9 on 2021-12-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_auto_20211202_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulepackage',
            old_name='content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='modulepackage',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='modulepackage',
            old_name='js_program',
            new_name='JSProgram',
        ),
        migrations.RenameField(
            model_name='modulepackage',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='modulepackage',
            old_name='url',
            new_name='URL',
        ),
        migrations.RenameField(
            model_name='modulepackage',
            old_name='version',
            new_name='Version',
        ),
    ]
