# Generated by Django 3.2.9 on 2021-12-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_alter_modulepackage_jsprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepackage',
            name='Content',
            field=models.CharField(blank=True, max_length=40000000, null=True),
        ),
        migrations.AlterField(
            model_name='modulepackage',
            name='URL',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
